Machine Learning using python

Numpy Module:-

Its an python library which is used to work with array.
Array-It collection of same datatype in in single variable.


Numpy has function for working in domain of linear algebra, fourier transform and matrices.


Numpy installation:

pip:- full form(preffered installer program)

cmd command:-
1. pip install numpy


Numpy funtion:-
1. declaring a ndarray (n-dimensional array)
2. To check the dimension of array arrayname.ndim
3. To convert ndarry from one formm to another form while declaration
    arrayname = ndarry([],ndmin=int)

4. accesing elemment using element

    1d array= arrayname[int]
    2d array= arrayname[int_of_list,int_of_element]
    3d array = arrayname[int_slice,int_of_list,int_of_element]


8. Slicing of array:- Means take particular element using slicing method.
    1d_array[start:end:step]
    2d_array[lisint,start:end:step]
    3d_array[slice,listint,start:end:step]

6. Shape of array= It refers to number of elements in each dimension
    array_name.shape

7. Reshaping of array= In here we change the size of an array acording to ous. MEans we can convert 1d array to 2d array
        It takes two arguments as 
        array_name(argument1,argument2)

        argument1= number of elements
        argumnet=number of elements
8. Iterating every element of array in form of list output using for loop

9. Concatation of n number of array in single array:-
    array_name = numpy.concatation((arrayname1,arrayname2,...))

In [ ]:
#importing numpy module

import numpy

#using numpy.array to declare ndarrray

arr= numpy.array([1,2,3,4,5])
print(arr)

#type of arr
type(arr)

In [1]:
import numpy as np
# In the above, we use the alias numpy as np

arr0 = np.array(0)  
arr1 = np.array([1, 2, 3, 4])  
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  
arr3 = np.array([[[1, 2,3], [3,3, 4], [5,3, 6]]])  
arr4= np.array([[[[1],[2],[3],[4]]]])
arr5= np.array([[[[[1,2],[2,3]]]]])

print(arr0, "0-dimensional array")
print(arr1, "1-dimensional array")
print(arr2, "2-dimensional array")
print(arr3, "3-dimensional array")

# To check the dimension of the array, we use the function arrayname.ndim
print("Dimensions of arr0:", arr0.ndim)
print("Dimensions of arr1:", arr1.ndim)
print("Dimensions of arr2:", arr2.ndim)
print("Dimensions of arr3:", arr3.ndim)
print("Dimensions of arr4=",arr4.ndim)
print("Dimensions of arr4=",arr5.ndim)


#converting 1 d array to 7 d array
arr12 = np.array([1,2,34],ndmin=5)
print(arr12)

#accesing a element of 1d array
arr1 = np.array([1, 2, 3, 4])  # 1-dimensional array
print(arr1[0])

#accessing a element from 2d array from 1st array and second element
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr2[0,1]) #here 1st argument for list 1 and second argument for accessin element

#accessing a element from 3d array from 2nd list and second element
arr3 = np.array([
    [[1,2,3], [4,5,6]],
    [[1,2,3], [7,8,9]]
    ])  
print(arr3[1,1,1]) #need practice in 3d

0 0-dimensional array
[1 2 3 4] 1-dimensional array
[[1 2 3 4]
 [5 6 7 8]] 2-dimensional array
[[[1 2 3]
  [3 3 4]
  [5 3 6]]] 3-dimensional array
Dimensions of arr0: 0
Dimensions of arr1: 1
Dimensions of arr2: 2
Dimensions of arr3: 3
Dimensions of arr4= 4
Dimensions of arr4= 5
[[[[[ 1  2 34]]]]]
1
2
8


In [ ]:
#slicing in array
import numpy as n

array1 = n.array([1,2,3,4,5,6,7,8])
print(array1[1:4])

#slicing the array using skipping in some part
print(array1[::2])

#slicing of 2d array
array2 = n.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2[1,:4])

In [ ]:
#shape of array:- argument 1st say numbr of list and 2nd argument tell number of elements
import numpy as n

arr = n.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

In [ ]:
#reshaping of array
import numpy as n
arr=n.array([1,2,3,4,5,6,7,8,9])
new_array= arr.reshape(3,3) #first argument take list number and 2nd argument take number of element

print(new_array)

#reshaping of array (slice,row,column) or (slice,list,element)
arr2=n.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array2= arr2.reshape(2,3,2)
print(new_array2)

In [ ]:
#iterating in ndarray
import numpy as n
array1= n.array([
    [1,2,3],
    [4,5,6]
])

for x in array1:
    print(x,sep=" ")

In [ ]:
#Joining two or more arrays in one form
import numpy as n
array1 = n.array([1,2,3,4])
array2= n.array([5,6,7,8])
array3=n.array([10,11])

array4= n.concatenate((array1,array2,arr))
print(array4)